import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <>
      <nav className="fixed top-0 left-0 right-0 z-[1000] bg-[var(--bg-primary)]/85 backdrop-blur-xl border-b border-[var(--border)]">
        <div className="max-w-[1200px] mx-auto px-6 h-[72px] flex items-center justify-between">
          <Link href="/" className="text-xl font-bold">Anomalist <span className="accent">Studios</span></Link>
          <Link href="/onboarding" className="btn btn-primary text-sm !py-2.5 !px-6">Get Started</Link>
        </div>
      </nav>

      <section className="pt-[140px] pb-[60px] text-center bg-[var(--bg-secondary)] border-b border-[var(--border)]">
        <h1 className="text-[clamp(2rem,4vw,3rem)] font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-[var(--text-muted)]">Last updated: April 2026</p>
      </section>

      <section className="py-[60px] px-6">
        <div className="max-w-[700px] mx-auto text-[0.95rem] text-[var(--text-secondary)] leading-[1.8] space-y-6">
          <p>These Terms of Service govern your use of anomalistmaximus.com and the Maximus content marketing platform operated by Anomalist Studios.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">1. Services</h2>
          <p>Anomalist Studios provides AI-powered content creation and marketing services through the Maximus platform. We generate social media posts, blog articles, email campaigns, ad copy, and related marketing materials based on your brand profile.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">2. Subscriptions & Billing</h2>
          <p>Paid plans are billed monthly through Stripe. Your first week of content is free after completing onboarding. You may cancel at any time — no contracts, no lock-in periods. Cancellation takes effect at the end of the current billing period.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">3. Content Ownership</h2>
          <p>All content generated by Maximus for your business is yours. You may use, edit, republish, or redistribute it in any way you choose. We retain no rights to your generated content after delivery.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">4. Your Responsibilities</h2>
          <p>You agree to provide accurate information during onboarding. You are responsible for reviewing content before publication. While Maximus generates platform-compliant content, you are ultimately responsible for what you post on your social media accounts.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">5. AI-Generated Content</h2>
          <p>Content produced by Maximus is generated by artificial intelligence and reviewed for quality. While we strive for accuracy, AI-generated content may occasionally contain errors. We recommend reviewing all content before publication.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">6. Limitation of Liability</h2>
          <p>Anomalist Studios is not liable for any indirect, incidental, or consequential damages arising from your use of our services. Our total liability shall not exceed the amount you paid us in the 12 months preceding any claim.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">7. Changes</h2>
          <p>We may update these terms from time to time. Material changes will be communicated via email. Continued use after changes are posted constitutes acceptance.</p>

          <h2 className="text-xl font-bold text-[var(--text-primary)] !mt-10">8. Contact</h2>
          <p>Questions? Email <a href="mailto:hello@anomaliststudios.com" className="text-[var(--accent)]">hello@anomaliststudios.com</a> or use our <Link href="/contact" className="text-[var(--accent)]">contact form</Link>.</p>
        </div>
      </section>

      <footer className="border-t border-[var(--border)] bg-[var(--bg-secondary)] py-8 px-6 text-center text-xs text-[var(--text-muted)]">
        © {new Date().getFullYear()} Anomalist Studios. All rights reserved.
      </footer>
    </>
  );
}
